version: '3.7'

services:

  auth:
    build: ./auth
    ports:
      - "8000:8000"
    volumes:
      - ./auth:/app
    environment:
      - FLASK_APP=auth.py
      - FLASK_ENV=development
    depends_on:
      - postgres

volumes:
  postgres_data:
